import {
  JWT_SECRET_DEV,
  ADMIN_JWT_SECRET_DEV,
  FACEBOOK_APP_ID_DEV,
  FACEBOOK_APP_SECRET_DEV,
  MONGODB_URI_DEV,
  ADMIN_REGISTER_SECRET_DEV
} from "./keys.dev";

// import {
//   JWT_SECRET_PROD,
//   ADMIN_JWT_SECRET_PROD,
//   FACEBOOK_APP_ID_PROD,
//   FACEBOOK_APP_SECRET_PROD,
//   ADMIN_REGISTER_SECRET_PROD,
//   MONGODB_URI_PROD
// } from "./keys.prod";

let JWT_SECRET: string;
let ADMIN_JWT_SECRET: string;
let FACEBOOK_APP_ID: string;
let FACEBOOK_APP_SECRET: string;
let MONGODB_URI: string;
let ADMIN_REGISTER_SECRET: string;

if (process.env.NODE_ENV === "production") {
  // JWT_SECRET = JWT_SECRET_PROD;
  // ADMIN_JWT_SECRET = ADMIN_JWT_SECRET_PROD;
  // FACEBOOK_APP_ID = FACEBOOK_APP_ID_PROD;
  // FACEBOOK_APP_SECRET = FACEBOOK_APP_SECRET_PROD;
  // MONGODB_URI = MONGODB_URI_PROD;
  // ADMIN_REGISTER_SECRET = ADMIN_REGISTER_SECRET_PROD;
} else {
  JWT_SECRET = JWT_SECRET_DEV;
  ADMIN_JWT_SECRET = ADMIN_JWT_SECRET_DEV;
  FACEBOOK_APP_ID = FACEBOOK_APP_ID_DEV;
  FACEBOOK_APP_SECRET = FACEBOOK_APP_SECRET_DEV;
  MONGODB_URI = MONGODB_URI_DEV;
  ADMIN_REGISTER_SECRET = ADMIN_REGISTER_SECRET_DEV;
}

const DEFAULT_POST_CREDIT = 10;
export {
  JWT_SECRET,
  ADMIN_JWT_SECRET,
  FACEBOOK_APP_ID,
  FACEBOOK_APP_SECRET,
  MONGODB_URI,
  DEFAULT_POST_CREDIT,
  ADMIN_REGISTER_SECRET
};
